[2024-09-25T05:56:12.282+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T05:56:12.294+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_articles_postgres_to_warehouse.extract_data manual__2024-09-25T05:56:10.917385+00:00 [queued]>
[2024-09-25T05:56:12.299+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_articles_postgres_to_warehouse.extract_data manual__2024-09-25T05:56:10.917385+00:00 [queued]>
[2024-09-25T05:56:12.299+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-25T05:56:12.306+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-09-25 05:56:10.917385+00:00
[2024-09-25T05:56:12.312+0000] {standard_task_runner.py:72} INFO - Started process 1093 to run task
[2024-09-25T05:56:12.316+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_articles_postgres_to_warehouse', 'extract_data', 'manual__2024-09-25T05:56:10.917385+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_kum.py', '--cfg-path', '/tmp/tmpy_77nfj4']
[2024-09-25T05:56:12.319+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask extract_data
[2024-09-25T05:56:12.376+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_articles_postgres_to_warehouse.extract_data manual__2024-09-25T05:56:10.917385+00:00 [running]> on host 800900cfd2b3
[2024-09-25T05:56:12.440+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_articles_postgres_to_warehouse' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T05:56:10.917385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T05:56:10.917385+00:00'
[2024-09-25T05:56:12.441+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T05:56:12.465+0000] {base.py:84} INFO - Retrieving connection 'postgres_source'
[2024-09-25T05:56:12.466+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/etl_kum.py", line 31, in extract_data
    src_conn = src_pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "localhost:5434" to address: Name or service not known

[2024-09-25T05:56:12.478+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_articles_postgres_to_warehouse, task_id=extract_data, run_id=manual__2024-09-25T05:56:10.917385+00:00, execution_date=20240925T055610, start_date=20240925T055612, end_date=20240925T055612
[2024-09-25T05:56:12.486+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T05:56:12.487+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task extract_data (could not translate host name "localhost:5434" to address: Name or service not known
; 1093)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/etl_kum.py", line 31, in extract_data
    src_conn = src_pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "localhost:5434" to address: Name or service not known

[2024-09-25T05:56:12.535+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-25T05:56:12.568+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T05:56:12.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
